import type { Config } from "tailwindcss";

export default {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#e8c170",
        "outline": "#7f7666",
        "surface-container-high": "#ffe3d0",
        "secondary-fixed": "#ffdbd0",
        "surface-tint": "#775a11",
        "surface-container-low": "#fff1e9",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed-variant": "#832600",
        "outline-variant": "#d1c5b3",
        "secondary": "#ab3500",
        "on-background": "#2f1500",
        "inverse-surface": "#49280b",
        "error-container": "#ffdad6",
        "on-primary-container": "#4c3700",
        "surface-container-highest": "#ffdcc3",
        "tertiary-fixed": "#ffddb2",
        "on-primary-fixed-variant": "#5b4300",
        "secondary-container": "#fe6a34",
        "tertiary": "#815500",
        "on-secondary-fixed": "#390c00",
        "surface": "#fff8f5",
        "inverse-primary": "#e8c170",
        "on-surface-variant": "#4d4638",
        "on-secondary-container": "#5d1900",
        "error": "#ba1a1a",
        "surface-variant": "#ffdcc3",
        "on-error-container": "#93000a",
        "background": "#fff8f5",
        "tertiary-container": "#d9982a",
        "surface-container": "#ffeadd",
        "surface-bright": "#fff8f5",
        "primary-fixed": "#ffdf9f",
        "primary-container": "#c4a052",
        "on-tertiary": "#ffffff",
        "on-surface": "#2f1500",
        "on-tertiary-fixed-variant": "#624000",
        "secondary-fixed-dim": "#ffb59d",
        "surface-dim": "#ffd1b0",
        "on-tertiary-fixed": "#291800",
        "on-primary-fixed": "#261a00",
        "tertiary-fixed-dim": "#ffb94c",
        "primary": "#775a11",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#ffede3",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#523500",
        "on-error": "#ffffff",
      },
      fontFamily: {
        headline: ["var(--font-garamond)", "EB Garamond", "serif"],
        body: ["var(--font-garamond)", "EB Garamond", "serif"],
        label: ["var(--font-garamond)", "EB Garamond", "serif"],
        editorial: ["var(--font-playfair)", "Playfair Display", "serif"],
        display: ["var(--font-playfair)", "Playfair Display", "serif"],
        accent: ["var(--font-playfair)", "Playfair Display", "serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      animation: {
        drift: "drift 15s linear infinite",
      },
      keyframes: {
        drift: {
          "0%": {
            transform: "translateY(-10vh) translateX(0) rotate(0deg)",
            opacity: "0",
          },
          "10%": { opacity: "0.8" },
          "90%": { opacity: "0.8" },
          "100%": {
            transform: "translateY(110vh) translateX(100px) rotate(360deg)",
            opacity: "0",
          },
        },
      },
    },
  },
  plugins: [],
} satisfies Config;
